/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewLoja;

import conexaoBanco.FabricaDeConexoes;
import model.RoupasDAO;
import beanLoja.RoupasVO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cliente
 */
public class TelaRoupa extends javax.swing.JFrame {

    /**
     * Creates new form TelaLojinha2
     */
    public TelaRoupa() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        QTD = new javax.swing.JTextField();
        Preco = new javax.swing.JTextField();
        BTAdicionar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BTExcluir = new javax.swing.JButton();
        BTPesquisar = new javax.swing.JButton();
        BTAlterar = new javax.swing.JButton();
        CodP = new javax.swing.JTextField();
        Cor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Categoria = new javax.swing.JTextField();
        CodFab = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BTExibir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRoupa = new javax.swing.JTable();
        txtCategoriaBusca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel14.setText(":)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Miriam", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 255));
        jLabel1.setText(" ========== Lojinha Galaxis ==========");

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Roupas");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Qtd Peça: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("Preço: ");

        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });

        BTAdicionar.setBackground(new java.awt.Color(255, 153, 153));
        BTAdicionar.setForeground(new java.awt.Color(51, 0, 51));
        BTAdicionar.setText("Adicionar");
        BTAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAdicionarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BTExcluir.setBackground(new java.awt.Color(255, 153, 153));
        BTExcluir.setForeground(new java.awt.Color(51, 0, 51));
        BTExcluir.setText("Excluir");
        BTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTExcluirActionPerformed(evt);
            }
        });

        BTPesquisar.setBackground(new java.awt.Color(204, 102, 255));
        BTPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        BTPesquisar.setText("Pesquisar");
        BTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTPesquisarActionPerformed(evt);
            }
        });

        BTAlterar.setBackground(new java.awt.Color(255, 153, 153));
        BTAlterar.setForeground(new java.awt.Color(51, 0, 51));
        BTAlterar.setText("Alterar");
        BTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAlterarActionPerformed(evt);
            }
        });

        Cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Código da Peça: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("Cor: ");

        CodFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodFabActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 153));
        jLabel7.setText("Cód. do Fabricante: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("Categoria: ");

        BTExibir.setBackground(new java.awt.Color(255, 153, 153));
        BTExibir.setForeground(new java.awt.Color(51, 0, 51));
        BTExibir.setText("Exibir");
        BTExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTExibirActionPerformed(evt);
            }
        });

        jTableRoupa.setBackground(new java.awt.Color(255, 204, 204));
        jTableRoupa.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jTableRoupa.setForeground(new java.awt.Color(0, 0, 0));
        jTableRoupa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "COR", "QTD", "PREÇO", "CATEGORIA", "COD.FAB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableRoupa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRoupaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableRoupaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableRoupa);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabel9.setText("Para pesquisar, insira no campo de busca apenas a categoria da peça:");

        jLabel10.setText(":(");

        jLabel11.setText(":)");

        jLabel12.setText(":)");

        jLabel13.setText(":)");

        jLabel15.setText(":)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 562, Short.MAX_VALUE)))
                                .addGap(112, 112, 112))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(QTD)
                                    .addComponent(Preco)
                                    .addComponent(CodP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Categoria)
                                    .addComponent(CodFab))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCategoriaBusca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BTExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(BTAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(BTExibir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BTAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)))
                                        .addGap(0, 216, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(453, 453, 453))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTAlterar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(CodP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(BTAdicionar)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BTExibir)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(BTExcluir)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CodFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTPesquisar)
                    .addComponent(txtCategoriaBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAdicionarActionPerformed
        // TODO add your handling code here:

        RoupasVO d = new RoupasVO();
        RoupasDAO dao = new RoupasDAO();

        d.setCodigo_da_peca(Integer.parseInt(CodP.getText()));
        d.setCor(Cor.getText());
        d.setQtd_peca(Integer.parseInt(QTD.getText()));
        d.setPreco(Double.parseDouble(Preco.getText()));
        d.setCategoria(Categoria.getText());
        d.setCodigo_fabricante(Integer.parseInt(CodFab.getText()));

        try {
            dao.create(d);
        } catch (Exception ex) {
            Logger.getLogger(TelaRoupa.class.getName()).log(Level.SEVERE, null, ex);
        }

        CodP.setText("");
        Cor.setText(String.valueOf(""));
        QTD.setText(String.valueOf(""));
        Preco.setText(String.valueOf(""));
        Categoria.setText(String.valueOf(""));
        CodFab.setText(String.valueOf(""));

    }//GEN-LAST:event_BTAdicionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Inicio obj = new Inicio();
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoActionPerformed

    private void CorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorActionPerformed

    private void CodFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodFabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodFabActionPerformed

    private void BTExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTExibirActionPerformed
        // TODO add your handling code here:
        CodP.setText("");
        Cor.setText(String.valueOf(""));
        QTD.setText(String.valueOf(""));
        Preco.setText(String.valueOf(""));
        Categoria.setText(String.valueOf(""));
        CodFab.setText(String.valueOf(""));
        carregaTabela();

    }//GEN-LAST:event_BTExibirActionPerformed

    private void BTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTExcluirActionPerformed
        // TODO add your handling code here:
        int k = jTableRoupa.getSelectedRow();
        int cod = (int) jTableRoupa.getValueAt(k, 0);
        String cor = (String) jTableRoupa.getValueAt(k, 1);
        int peca = (int) jTableRoupa.getValueAt(k, 2);
        double preco = (double) jTableRoupa.getValueAt(k, 3);
        String categoria = (String) jTableRoupa.getValueAt(k, 4);
        int cod_fab = (int) jTableRoupa.getValueAt(k, 5);
        Connection con = null;
        try {
            con = FabricaDeConexoes.getConnection();
        } catch (Exception ex) {
            Logger.getLogger(TelaRoupa.class.getName()).log(Level.SEVERE, null, ex);
        }
        Statement stmt = null;
        try {
            stmt = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(TelaRoupa.class.getName()).log(Level.SEVERE, null, ex);
        }

        String sql1 = "DELETE FROM roupa WHERE codigo_da_peça = " + cod + " ";
        String sql2 = "DELETE FROM roupa WHERE cor = " + cor + " ";
        String sql3 = "DELETE FROM roupa WHERE peça = " + peca + " ";
        String sql4 = "DELETE FROM roupa WHERE preço = " + preco + " ";
        String sql5 = "DELETE FROM roupa WHERE categoria = " + categoria + " ";
        String sql6 = "DELETE FROM roupa WHERE código_do_fornecedor = " + cod_fab + " ";

        try {
            stmt.executeUpdate(sql1);
            JOptionPane.showMessageDialog(this, "Excluído com Sucesso!");
            stmt.executeUpdate(sql2);
            stmt.executeUpdate(sql3);
            stmt.executeUpdate(sql4);
            stmt.executeUpdate(sql5);
            stmt.executeUpdate(sql6);

            if (jTableRoupa.getSelectedRow() >= 0) {
                jTableRoupa.remove(jTableRoupa.getSelectedRow());
            }

        } catch (SQLException ex) {
            System.out.println("");
        }
        CodP.setText("");
        Cor.setText(String.valueOf(""));
        QTD.setText(String.valueOf(""));
        Preco.setText(String.valueOf(""));
        Categoria.setText(String.valueOf(""));
        CodFab.setText(String.valueOf(""));

    }//GEN-LAST:event_BTExcluirActionPerformed

    private void BTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAlterarActionPerformed
        // TODO add your handling code here:
        RoupasVO d = new RoupasVO();
        RoupasDAO dao = new RoupasDAO();
        int index;
        index = jTableRoupa.getSelectedRow();

        try {
            d = dao.listar().get(index);
        } catch (Exception ex) {
            Logger.getLogger(TelaRoupa.class.getName()).log(Level.SEVERE, null, ex);
        }

        d.setCor(Cor.getText());
        d.setQtd_peca(Integer.parseInt(QTD.getText()));
        d.setPreco(Double.parseDouble(Preco.getText()));
        d.setCategoria(Categoria.getText());
        d.setCodigo_fabricante(Integer.parseInt(CodFab.getText()));

        try {
            dao.alterar(d);
        } catch (Exception ex) {
            Logger.getLogger(TelaRoupa.class.getName()).log(Level.SEVERE, null, ex);
        }

        CodP.setText("");
        Cor.setText(String.valueOf(""));
        QTD.setText(String.valueOf(""));
        Preco.setText(String.valueOf(""));
        Categoria.setText(String.valueOf(""));
        CodFab.setText(String.valueOf(""));

        carregaTabela();
    }//GEN-LAST:event_BTAlterarActionPerformed

    private void jTableRoupaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRoupaMouseClicked
        // TODO add your handling code here:
        RoupasVO d = new RoupasVO();
        RoupasDAO dao = new RoupasDAO();
        int index = jTableRoupa.getSelectedRow();

        try {
            d = dao.listar().get(index);
        } catch (Exception ex) {
            Logger.getLogger(TelaRoupa.class.getName()).log(Level.SEVERE, null, ex);
        }

        CodP.setText(String.valueOf(d.getCodigo_da_peca()));
        Cor.setText(String.valueOf(d.getCor()));
        QTD.setText(String.valueOf(d.getQtd_peca()));
        Preco.setText(String.valueOf(d.getPreco()));
        Categoria.setText(String.valueOf(d.getCategoria()));
        CodFab.setText(String.valueOf(d.getCodigo_fabricante()));

    }//GEN-LAST:event_jTableRoupaMouseClicked

    private void BTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTPesquisarActionPerformed
        try {
            // TODO add your handling code here:
            pesquisaItem(txtCategoriaBusca.getText());
        } catch (Exception ex) {
            Logger.getLogger(TelaRoupa.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtCategoriaBusca.setText(String.valueOf(""));
    }//GEN-LAST:event_BTPesquisarActionPerformed

    private void jTableRoupaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRoupaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableRoupaMousePressed

    private void pesquisaItem(String tipo) throws Exception {
        DefaultTableModel modelo = (DefaultTableModel) jTableRoupa.getModel();
        modelo.setNumRows(0);
        RoupasDAO dao = new RoupasDAO();
        RoupasVO d = new RoupasVO();

        for (RoupasVO rs : dao.pesquisar(tipo)) {
            modelo.addRow(new Object[]{
                rs.getCodigo_da_peca(),
                rs.getCor(),
                rs.getQtd_peca(),
                rs.getPreco(),
                rs.getCategoria(),
                rs.getCodigo_fabricante()
            });
        }
    }

    private void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTableRoupa.getModel();
        modelo.setNumRows(0);

        jTableRoupa.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTableRoupa.getColumnModel().getColumn(1).setPreferredWidth(20);
        jTableRoupa.getColumnModel().getColumn(2).setPreferredWidth(20);
        jTableRoupa.getColumnModel().getColumn(3).setPreferredWidth(20);
        jTableRoupa.getColumnModel().getColumn(4).setPreferredWidth(20);
        jTableRoupa.getColumnModel().getColumn(5).setPreferredWidth(20);

        try {
            Connection con = FabricaDeConexoes.getConnection();
            PreparedStatement pstm;
            ResultSet rs;

            pstm = con.prepareStatement("select * from roupa");
            rs = pstm.executeQuery();

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getInt(3),
                    rs.getDouble(4),
                    rs.getString(5),
                    rs.getInt(6)
                });
            }
        } catch (Exception ErroSQL) {
            System.out.println(" ");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRoupa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAdicionar;
    private javax.swing.JButton BTAlterar;
    private javax.swing.JButton BTExcluir;
    private javax.swing.JButton BTExibir;
    private javax.swing.JButton BTPesquisar;
    private javax.swing.JTextField Categoria;
    private javax.swing.JTextField CodFab;
    private javax.swing.JTextField CodP;
    private javax.swing.JTextField Cor;
    private javax.swing.JTextField Preco;
    private javax.swing.JTextField QTD;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRoupa;
    private javax.swing.JTextField txtCategoriaBusca;
    // End of variables declaration//GEN-END:variables

    private void setcodigo_de_cadastro(int parseInt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void settelefone(int parseInt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
